#!/bin/bash
set -x
rm -rf elm-stuff
./docker-elm-package-install.py elm-lang/core 2.1.0
./docker-elm-package-install.py evancz/elm-html 3.0.0
./docker-elm-package-install.py evancz/elm-http 1.0.0
./docker-elm-package-install.py evancz/virtual-dom 1.2.3
